# Generated by Django 5.2.4 on 2025-07-19 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='empresa',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='empresa',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
