# Generated by Django 5.2.4 on 2025-07-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_cuentaporcobrar_empresa_cuentaporpagar_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
