# Generated by Django 5.2.4 on 2025-07-20 17:33

import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_pago_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(default=finanzas.models.hoy_fecha),
        ),
    ]
