# Generated by Django 5.2.4 on 2025-07-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_pago_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='asiento_contable_creado',
            field=models.BooleanField(default=False),
        ),
    ]
