# Generated by Django 5.2.4 on 2025-07-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'sucursal', 'lote', 'fecha_vencimiento')},
        ),
    ]
