# Generated by Django 5.2.4 on 2025-07-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_razon_social'),  # <-- Añade la migración correcta aquí
        ('inventario', '0002_alter_inventario_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveSATProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Clave SAT Producto',
                'verbose_name_plural': 'Claves SAT Productos',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='ClaveSATUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Clave SAT Unidad',
                'verbose_name_plural': 'Claves SAT Unidades',
                'ordering': ['clave'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='clave_sat',
            field=models.ForeignKey(blank=True, help_text='Clave SAT del producto o servicio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.clavesatproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, help_text='Clave SAT de unidad de medida', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.clavesatunidad'),
        ),
    ]
