# Generated by Django 5.2.4 on 2025-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_clavesatproducto_clavesatunidad_producto_clave_sat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clavesatproducto',
            name='clave',
            field=models.CharField(max_length=21, unique=True),
        ),
        migrations.AlterField(
            model_name='clavesatunidad',
            name='clave',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
