
# --- /home/runner/workspace/documentos/__init__.py ---



# --- /home/runner/workspace/documentos/admin.py ---
from django.contrib import admin

# Register your models here.



# --- /home/runner/workspace/documentos/apps.py ---
from django.apps import AppConfig


class DocumentosConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'documentos'



# --- /home/runner/workspace/documentos/tests.py ---
from django.test import TestCase

# Create your tests here.



# --- /home/runner/workspace/documentos/models.py ---
# documentos/models.py

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone


class DocumentoFiscal(models.Model):
    TIPO_DOCUMENTO_CHOICES = [
        ('CFDI', 'CFDI'),
        ('XML', 'XML'),
        ('PDF', 'PDF'),
        ('OTRO', 'Otro'),
    ]

    tipo_documento = models.CharField(
        max_length=10,
        choices=TIPO_DOCUMENTO_CHOICES,
        default='CFDI',
        help_text="Tipo de documento fiscal (CFDI, XML, PDF, etc.)"
    )
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        help_text="Tipo de modelo referenciado (venta, compra, asiento, etc.)"
    )
    object_id = models.PositiveIntegerField(
        help_text="ID de la entidad relacionada"
    )
    referencia = GenericForeignKey('content_type', 'object_id')

    archivo = models.FileField(
        upload_to='documentos_fiscales/%Y/%m/%d/',
        help_text="Archivo digital del documento (PDF, XML, etc.)"
    )
    fecha_emision = models.DateField(
        default=timezone.now,
        help_text="Fecha de emisión del documento"
    )

    class Meta:
        verbose_name = "Documento Fiscal"
        verbose_name_plural = "Documentos Fiscales"
        indexes = [
            models.Index(fields=['tipo_documento']),
            models.Index(fields=['content_type', 'object_id']),
        ]
        ordering = ['-fecha_emision']

    def __str__(self):
        return f"{self.get_tipo_documento_display()} - Ref: {self.referencia} - {self.fecha_emision}"



# --- /home/runner/workspace/documentos/migrations/__init__.py ---



# --- /home/runner/workspace/documentos/migrations/0001_initial.py ---
# Generated by Django 5.2.4 on 2025-07-30 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CFDI', 'CFDI'), ('XML', 'XML'), ('PDF', 'PDF'), ('OTRO', 'Otro')], default='CFDI', help_text='Tipo de documento fiscal (CFDI, XML, PDF, etc.)', max_length=10)),
                ('object_id', models.PositiveIntegerField(help_text='ID de la entidad relacionada')),
                ('archivo', models.FileField(help_text='Archivo digital del documento (PDF, XML, etc.)', upload_to='documentos_fiscales/%Y/%m/%d/')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión del documento')),
                ('content_type', models.ForeignKey(help_text='Tipo de modelo referenciado (venta, compra, asiento, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscales',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['tipo_documento'], name='documentos__tipo_do_1d0d20_idx'), models.Index(fields=['content_type', 'object_id'], name='documentos__content_0ded15_idx')],
            },
        ),
    ]



# --- /home/runner/workspace/documentos/views/__init_.py ---


