
# --- /home/runner/workspace/rrhh/__init__.py ---



# --- /home/runner/workspace/rrhh/admin.py ---
from django.contrib import admin

# Register your models here.



# --- /home/runner/workspace/rrhh/apps.py ---
from django.apps import AppConfig


class RrhhConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'rrhh'



# --- /home/runner/workspace/rrhh/tests.py ---
from django.test import TestCase

# Create your tests here.



# --- /home/runner/workspace/rrhh/models.py ---
# rrhh/models.py

from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone

class Empleado(models.Model):
    empresa = models.ForeignKey('core.Empresa', on_delete=models.CASCADE, related_name='empleados')
    nombre = models.CharField(max_length=200)
    rfc = models.CharField(max_length=13, blank=True, null=True)
    puesto = models.CharField(max_length=100)
    salario = models.DecimalField(max_digits=14, decimal_places=2)

    def clean(self):
        if self.salario < 0:
            raise ValidationError("El salario no puede ser negativo.")


    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"
        ordering = ['nombre']
        indexes = [
            models.Index(fields=['empresa', 'nombre']),
        ]

    def __str__(self):
        return f"{self.nombre} - {self.puesto}"


class Nomina(models.Model):
    ESTADO_CHOICES = [
        ('PENDIENTE', 'Pendiente'),
        ('PAGADA', 'Pagada'),
        ('CANCELADA', 'Cancelada'),
    ]

    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='nominas')
    periodo = models.CharField(max_length=50, help_text="Ejemplo: 'Julio 2025'")
    total = models.DecimalField(max_digits=14, decimal_places=2)
    estado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='PENDIENTE')

    class Meta:
        verbose_name = "Nómina"
        verbose_name_plural = "Nóminas"
        ordering = ['-periodo']
        indexes = [
            models.Index(fields=['empleado', 'periodo']),
            models.Index(fields=['estado']),
        ]

    def __str__(self):
        return f"Nómina {self.periodo} - {self.empleado.nombre} - {self.estado}"


class Asistencia(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, related_name='asistencias')
    fecha = models.DateField()
    hora_entrada = models.TimeField()
    hora_salida = models.TimeField()

    class Meta:
        verbose_name = "Asistencia"
        verbose_name_plural = "Asistencias"
        ordering = ['-fecha']
        indexes = [
            models.Index(fields=['empleado', 'fecha']),
        ]

    def __str__(self):
        return f"Asistencia {self.empleado.nombre} - {self.fecha}"



# --- /home/runner/workspace/rrhh/migrations/__init__.py ---



# --- /home/runner/workspace/rrhh/migrations/0001_initial.py ---
# Generated by Django 5.2.4 on 2025-07-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('puesto', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text="Ejemplo: 'Julio 2025'", max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-periodo'],
            },
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['empresa', 'nombre'], name='rrhh_emplea_empresa_30960a_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['empleado', 'fecha'], name='rrhh_asiste_emplead_72a5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['empleado', 'periodo'], name='rrhh_nomina_emplead_a511c4_idx'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['estado'], name='rrhh_nomina_estado_8abe47_idx'),
        ),
    ]



# --- /home/runner/workspace/rrhh/views/__init_.py ---


