# Generated by Django 5.2.4 on 2025-07-25 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CFDI', 'CFDI'), ('XML', 'XML'), ('PDF', 'PDF'), ('OTRO', 'Otro')], default='CFDI', help_text='Tipo de documento fiscal (CFDI, XML, PDF, etc.)', max_length=10)),
                ('object_id', models.PositiveIntegerField(help_text='ID de la entidad relacionada')),
                ('archivo', models.FileField(help_text='Archivo digital del documento (PDF, XML, etc.)', upload_to='documentos_fiscales/%Y/%m/%d/')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión del documento')),
                ('content_type', models.ForeignKey(help_text='Tipo de modelo referenciado (venta, compra, asiento, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscales',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['tipo_documento'], name='documentos__tipo_do_1d0d20_idx'), models.Index(fields=['content_type', 'object_id'], name='documentos__content_0ded15_idx')],
            },
        ),
    ]
