# Generated by Django 5.2.4 on 2025-07-30 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reintentos_timbrado', models.PositiveIntegerField(default=0)),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('xml', models.FileField(blank=True, null=True, upload_to='cfdi_xmls/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='cfdi_pdfs/')),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TIMBRADO', 'Timbrado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('NOTA_CREDITO', 'Nota de Crédito'), ('RECIBO_NOMINA', 'Recibo de Nómina')], default='FACTURA', max_length=20)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('folio', models.PositiveIntegerField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], help_text='Método de pago según catálogo SAT (PUE, PPD)', max_length=3, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('01', 'Efectivo'), ('02', 'Cheque nominativo'), ('03', 'Transferencia electrónica de fondos'), ('04', 'Tarjeta de crédito'), ('05', 'Monedero electrónico'), ('06', 'Dinero electrónico'), ('08', 'Vales de despensa'), ('12', 'Dación en pago'), ('13', 'Pago por subrogación'), ('14', 'Pago por consignación'), ('15', 'Condonación'), ('17', 'Compensación'), ('23', 'Novación'), ('24', 'Confusión'), ('25', 'Remisión de deuda'), ('26', 'Prescripción o caducidad'), ('27', 'A satisfacción del acreedor'), ('28', 'Tarjeta de débito'), ('29', 'Tarjeta de servicios'), ('30', 'Aplicación de anticipos'), ('31', 'Intermediario de pagos'), ('99', 'Por definir')], help_text='Forma de pago clave SAT (Ej: 01 Efectivo, 03 Transferencia)', max_length=3, null=True)),
                ('exportacion', models.CharField(choices=[('01', 'No aplica'), ('02', 'Definitiva'), ('03', 'Temporal')], default='01', help_text='Exportación según el catálogo SAT c_Exportacion', max_length=2)),
                ('facturama_id', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, choices=[('01', 'Comprobante emitido con errores con relación'), ('02', 'Comprobante emitido con errores sin relación'), ('03', 'No se llevó a cabo la operación'), ('04', 'Operación nominativa relacionada en la factura global')], max_length=3, null=True)),
                ('sustitucion_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='facturacion_estado_4c1711_idx'), models.Index(fields=['tipo'], name='facturacion_tipo_904fe7_idx')],
            },
        ),
    ]
