# Generated by Django 5.2.4 on 2025-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantefiscal',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comprobantefiscal',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
