# Generated by Django 5.2.4 on 2025-07-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_comprobantefiscal_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantefiscal',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to='cfdi_xmls/'),
        ),
    ]
