# Generated by Django 5.2.4 on 2025-07-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0002_empresa_razon_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único, ej: 1020', max_length=10)),
                ('nombre', models.CharField(help_text='Ej: Banco BBVA', max_length=255)),
                ('clasificacion', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=20)),
                ('es_auxiliar', models.BooleanField(default=True, help_text='Marca si la cuenta es de movimiento o de agrupación')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.RenameIndex(
            model_name='detalleasiento',
            new_name='contabilida_asiento_f6ba5e_idx',
            old_name='contabilida_asiento_1bd092_idx',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='es_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='referencia_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID del objeto origen (ej: pago, compra, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='referencia_tipo',
            field=models.CharField(blank=True, help_text="Tipo de objeto origen (ej: 'Pago', 'Compra')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='total_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='total_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detalleasiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional para este movimiento.', null=True),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['referencia_tipo', 'referencia_id'], name='contabilida_referen_82230c_idx'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_contables', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='contabilidad.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='detalleasiento',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuentacontable'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentacontable',
            unique_together={('codigo', 'empresa')},
        ),
    ]
