# Generated by Django 5.2.4 on 2025-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cuentacontable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
    ]
