# Generated by Django 5.2.4 on 2025-07-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_asientocontable_conciliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='conciliado',
            field=models.BooleanField(default=False, help_text='Indica si el asiento está conciliado o cerrado'),
        ),
    ]
