# Generated by Django 5.2.4 on 2025-08-01 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre amigable del reporte.', max_length=255)),
                ('tipo', models.CharField(choices=[('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('INVENTARIO', 'Inventario'), ('FLUJO_CAJA', 'Flujo de Caja'), ('KPI', 'Indicador'), ('DASHBOARD', 'Dashboard'), ('OTRO', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('GENERANDO', 'Generando'), ('COMPLETO', 'Completo'), ('FALLIDO', 'Fallido')], default='GENERANDO', max_length=20)),
                ('filtros_usados', models.JSONField(help_text='Filtros aplicados al generar el reporte (fecha, usuario, etc.)')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/pdf/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excel/')),
                ('archivo_csv', models.FileField(blank=True, null=True, upload_to='reportes/csv/')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-generado_en'],
            },
        ),
    ]
