"""
Django settings for nova_erp_total project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import os

# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration
# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

import sentry_sdk
import base64

sentry_sdk.init(
    dsn=
    "https://59a6b3f5a097d60c09ff94e6a517e6f4@o4509617180311552.ingest.us.sentry.io/4509617183981568",
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)

ALLOWED_IPS = ['190.10.20.30', '10.0.0.1']  # oficina, cliente


class IPWhitelistMiddleware:

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        ip = request.META.get('REMOTE_ADDR')
        if ip not in ALLOWED_IPS:
            from django.http import HttpResponseForbidden
            return HttpResponseForbidden("IP no autorizada")
        return self.get_response(request)


# sentry_sdk.init(
#     dsn="https://tu_clave@o0.ingest.sentry.io/proyecto-id",
#     integrations=[DjangoIntegration()],
#     traces_sample_rate=1.0,  # o 0.1 para producción
#     send_default_pii=True,
# )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qamg-)bhge&qtj+!*ayn4+*vp6=u708^1^$nu5hf7#1refr+do'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'accounts.apps.AccountsConfig',
    'django_extensions',
    # Apps locales
    # 'accounts',
    'inventario',
    # 'ventas',
    'ventas.apps.VentasConfig',
    'compras',
    'finanzas',
    # 'contabilidad',
    'contabilidad.apps.ContabilidadConfig',
    'rrhh',
    'documentos',
    'core',
    'facturacion',
    'reportes',

    # REST Framework y JWT
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]
FACTURAMA_USER = "EKU9003173C9222"
FACTURAMA_PASSWORD = "Losy990209bn7"
# FACTURAMA_API_URL = "https://apisandbox.facturama.mx/3/cfdis/3.3/"
FACTURAMA_API_URL = "https://apisandbox.facturama.mx/3/cfdis"

# FACTURAMA_API_URL = "https://api.facturama.mx"  # o sandbox si estás probando
# FACTURAMA_CREDENTIALS = f"<Base64 {FACTURAMA_USER}:{FACTURAMA_PASSWORD}>"
FACTURAMA_CREDENTIALS = base64.b64encode(f"{FACTURAMA_USER}:{FACTURAMA_PASSWORD}".encode()).decode()


INSTALLED_APPS += ['django_filters', 'drf_spectacular']

AUTH_USER_MODEL = 'accounts.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # CORS
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #AUDITARIA MIDDLEWARE
    'core.middleware.auditoria.AuditoriaMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS':
    ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS':
    'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':
    25,  # Páginas de 20 resultados
    'DEFAULT_AUTHENTICATION_CLASSES':
    ('rest_framework_simplejwt.authentication.JWTAuthentication', ),
    'DEFAULT_PERMISSION_CLASSES':
    ('rest_framework.permissions.IsAuthenticated', ),
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_SCHEMA_CLASS':
    'accounts.schema.CustomAutoSchema',
    #CIBERCEGURIDAD VS FUERZA BRUTA
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/minute',  # ajusta según tu tráfico real
        'anon': '10/minute',  # no autenticados (login, reset)
        'login': '5/minute',  # 👈 solo para login
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Nova ERP API',
    'DESCRIPTION': 'Documentación de la API del sistema Nova ERP',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA':
    True,  # 👈 Esta línea permite conectar correctamente con /docs/
    'SCHEMA_PATH_PREFIX': '/api/schema/',
    'PARSER_CLASSES': ['drf_spectacular.parsers.YAMLParser'],
    'RENDERER_CLASSES': ['drf_spectacular.renderers.YAMLRenderer'],
}

# settings.py DESPUES SE DESCOMENTARA CON LOGINS CREO
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'secret_key_here',
    # 'ACCESS_TOKEN_LIFETIME': timedelta(days=1),        # antes: 5 minutos
    # 'REFRESH_TOKEN_LIFETIME': timedelta(days=30),      # antes: 1 día
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

DEBUG = True

if DEBUG:
    SIMPLE_JWT['ACCESS_TOKEN_LIFETIME'] = timedelta(days=1)
    SIMPLE_JWT['REFRESH_TOKEN_LIFETIME'] = timedelta(days=30)
else:
    SIMPLE_JWT['ACCESS_TOKEN_LIFETIME'] = timedelta(minutes=5)
    SIMPLE_JWT['REFRESH_TOKEN_LIFETIME'] = timedelta(days=1)

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.microsoft.MicrosoftOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1039784506241-ehqp78nga5sh3rkumrii0ltkgcd46bph.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'nova_erp_total.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # Agrega esta línea
                'social_django.context_processors.login_redirect',  # Y esta
            ],
        },
    },
]

WSGI_APPLICATION = 'nova_erp_total.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '<tu-client-id-google>'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '<tu-client-secret-google>'

SOCIAL_AUTH_MICROSOFT_KEY = '<tu-client-id-microsoft>'
SOCIAL_AUTH_MICROSOFT_SECRET = '<tu-client-secret-microsoft>'

CSRF_TRUSTED_ORIGINS = [
    "https://fca3faea-e64a-4f83-a448-762fa6e71df4-00-1kkfg9j97gplb.spock.replit.dev",
    # puedes agregar más orígenes si usas otros subdominios o entornos
]

# --------------------------------------------------------------------------------
# Cabeceras HTTP seguras (anti XSS, Clickjacking, etc.)
# --------------------------------------------------------------------------------
# Protege contra XSS
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Previene que tu sitio sea cargado en un iframe (clickjacking)
X_FRAME_OPTIONS = 'DENY'

# Política del encabezado Referer
SECURE_REFERRER_POLICY = 'same-origin'

# Seguridad estricta solo si usas HTTPS
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Cookies seguras si usas JWT en cookies (no aplica por default)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# Permite solo tu frontend (React, Vue, etc.)
CORS_ALLOWED_ORIGINS = [
    "https://fca3faea-e64a-4f83-a448-762fa6e71df4-00-1kkfg9j97gplb.spock.replit.dev",
    "https://tusitio-frontend.com",
    "https://erpcliente.com",
]

# Evita permitir todos los orígenes (¡no usar en producción!)
CORS_ALLOW_ALL_ORIGINS = False

# Métodos permitidos
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# Headers permitidos
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "accept",
    "origin",
    "user-agent",
]



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yaview.lomeli@gmail.com'
EMAIL_HOST_PASSWORD = 'ncvs lfro srke goiq'
DEFAULT_FROM_EMAIL = 'Nova_erp_api <yaview.lomeli@gmail.com>'
