# Generated by Django 5.2.4 on 2025-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
