# Generated by Django 5.2.4 on 2025-07-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_detallecompra_fecha_vencimiento_detallecompra_lote'),
        ('inventario', '0002_alter_inventario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallecompra',
            unique_together={('compra', 'producto', 'lote', 'fecha_vencimiento')},
        ),
    ]
