# Generated by Django 5.2.4 on 2025-07-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detallecompra_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
